require "open-uri"
require "nokogiri"
require "pry"
require "date"

require_relative "featured_wiki/version"
require_relative "./featured_wiki/cli"
require_relative "./featured_wiki/article"
require_relative "./featured_wiki/scraper"
require_relative "./featured_wiki/this-month"
